Add support for Django 4.2
django-json-api/django-rest-framework-json-api pull request #1142
Opened 2023-04-04 13:39 UTC by Tenzer

Allows library to be installed with Django 4.2.

## Description of the Change

This broadens the range of Django versions this library allows to be installed alongside to include Django 4.2 and any bugfix releases of it.

It also disables the use of the now deprecated `UnsaltedMD5PasswordHasher` hashing algorithm when running tests, as it otherwise would raise deprecation warnings. This will make the tests slightly slower since the default password hashing algorithm uses more resources, but it shouldn't have a big impact all in all as the tests run pretty quickly regardless.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [x] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

2023-04-04 14:03 UTC, sliverc requested changes
Thanks for working on this. Looks good overall just make sure you do not drop tests for Django 4.1.

2023-04-04 14:03 UTC, sliverc commented on tox.ini
> -    py{38,39,310,311}-django41-drf{314,master},
we should not remove Django 4.1 from the testgrid

2023-04-04 14:03 UTC, sliverc commented on tox.ini
> -    django41: Django>=4.1,<4.2
as above Django 4.1 should remain

2023-04-04 14:03 UTC, sliverc commented on tox.ini
> -[testenv:py{38,39,310,311}-django41-drfmaster]
Django 4.1 should remain

2023-04-04 14:12 UTC, Tenzer commented
Thank you for the review. I have reinstated the Django 4.1 tests now.

2023-04-04 14:47 UTC, sliverc approved these changes
Thanks. It looks good now.

2023-04-04 14:47 UTC, merged

2023-04-04 14:48 UTC, Tenzer commented
Great, thanks! Do you know when a new release might be cut? This would be blocking any users of the library from upgrading to Django 4.2.

2023-04-05 14:18 UTC, sliverc commented
This kind of depends on when DRF will release a new version supporting Django 4.2. @auvipy Do you have more information when there will be a new DRF release?

2023-04-05 14:28 UTC, Tenzer commented
It looks like https://github.com/encode/django-rest-framework/pull/8794 is the relevant issue to track regards a new release.

2023-04-08 08:51 UTC, auvipy commented
> This kind of depends on when DRF will release a new version supporting Django 4.2. @auvipy Do you have more information when there will be a new DRF release?

I contacted with Tom but he seem to be busy. I hoe we can cut a release in late this month or early next month.

2023-05-21 22:18 UTC, abmohan commented
Thanks for working on this. I'm looking forward to upgrading to django 4.2. What's the release schedule looking like? How long do you think we'd have to wait for this?

2023-06-12 14:05 UTC, sliverc commented
@abmohan We are still waiting on DRF to release 3.15 with Django 4.2 support. @auvipy Do you have any update when this will be ready? Thanks.

2023-08-09 14:42 UTC, elanqo commented
@sliverc, When do you anticipate publishing these changes to PyPI?

2023-08-10 07:39 UTC, max-wittig commented
@sliverc We're using DRF with 4.2 in production from the latest release. According to their README it should be already supported. Sorry, if I missed something here and just jumped in without knowning something important. Just wanted to state the obvious (it works with 4.2) 😄

2023-08-25 13:59 UTC, sliverc commented
DRF 3.15 seems to take longer than anticipated. So I released it [now](https://github.com/django-json-api/django-rest-framework-json-api/releases/tag/v6.1.0).