Introduce pre-commit to simplify contributions
django-json-api/django-rest-framework-json-api pull request #866
Opened 2020-11-22 21:08 UTC by sliverc

Fixes #861

## Description of the Change

Add pre-commit for editor independent checking of linting and formatting of code before committing changes to git.

I have added a [pre-commit](https://pre-commit.com/#usage) configuration which uses the locally resp. in the virtual environment installed version of flake8, isort and black. pre-commit also has a way of handling the installation of such tools. However PyUp cannot update those version references and we might end up with different version in pre-commit and requirements.txt which we should avoid.  

The only down side to run tools locally is that a virtual env needs to be activated before committing. This needs to be the case anyway to run tests.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [x] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

2020-11-22 22:58 UTC, n2ygk requested changes
Consider adding something like the following to tox.ini as a mean of making it easy for someone to set up the venv:
```
[testenv:devenv]
envdir = env
basepython = python3.6
usedevelop = True
deps =
    -rrequirements.txt
commands =
    /usr/bin/printf '\n\033[0;31m  dont forget to source env/bin/activate\033[0m\n'
```

2020-12-03 18:26 UTC, sliverc commented
@n2ygk Actually to run tox there is no need to create a virtual env as tox manages this for the user. DRF also suggests to install [tox](https://github.com/encode/django-rest-framework/blob/master/CONTRIBUTING.md#running-against-multiple-environments) globally. It is a good reminder though that I missed out on documenting how to use tox. I have integrated it now the same way as DRF documented it.

2020-12-05 18:27 UTC, n2ygk commented on docs/CONTRIBUTING.md
> +     # Setup the virtual environment
@sliverc my point of `tox -e devenv` is you can turn these several steps into one.

2020-12-05 18:28 UTC, n2ygk approved these changes
The tox -e devenv stuff can wait for another PR if you see the value of it.

2020-12-05 18:28 UTC, merged