Render meta fields of included resource
django-json-api/django-rest-framework-json-api pull request #883
Opened 2021-01-13 13:02 UTC by mast22

## Fixes
Added meta object into included resources
## Description of the Change
When adding serializer as a field the meta fields are not rendered, This change provides the rendering capability, test and some fixes of related tests. 
## Checklist

- [X] PR only contains one change (considered splitting up PR)
- [X] unit-test added
- [ ] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [X] author name in `AUTHORS`

2021-01-14 08:08 UTC, sliverc requested changes
Thanks a lot for this PR. This brings certainly more consistency to DJA.

I have added some inline comments. Please also add a changelog entry. Thanks.

2021-01-14 08:08 UTC, sliverc commented on rest_framework_json_api/renderers.py
> +                    meta = cls.extract_meta(field, serializer_data)
Shouldn't this logic be moved into `build_json_resource_obj`? See comment above.

2021-01-14 08:08 UTC, sliverc commented on rest_framework_json_api/renderers.py
> +                        meta = cls.extract_meta(field, serializer_resource)
Shouldn't this logic be moved into build_json_resource_obj? Even the formatting of the field names could be moved there. This is just at a quick glance maybe in practice there are more hurdles.

2021-01-14 08:09 UTC, sliverc commented on example/models.py
> +from datetime import datetime
you need to run `isort` to make CI happy.

2021-02-10 18:37 UTC, sliverc commented on rest_framework_json_api/renderers.py
> +                        meta = cls.extract_meta(field, serializer_resource)
I found some time to look into this and I was able to move the extract meta logic into the `build_json_resource_obj` and updated your PR.

2021-02-10 18:39 UTC, sliverc approved these changes

2021-02-10 18:39 UTC, sliverc commented
Thanks for your contributions. As mentioned above I adjusted your PR a bit but all the rest looked good and ready for merging.

2021-02-10 18:40 UTC, merged

2021-03-16 08:25 UTC, mast22 commented
Thanks, and sorry I could not complete it myself. Glad i could help